### ISSUE TITLE
gui cannot be opened

### ISSUE THREAD

**Issue by zboing** [idzresearch/aab-to-apk-converter#3]
**Describe the bug**
gui cannot be opened

**To Reproduce**
1. open gui in terminal to see error messages'
2. the terminal shows;
Error loading Python DLL 'C:\AAB2APK_v1\BundleToolGUI\python39.dll'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.
C:\AAB2APK_v1\BundleToolGUI>

**Expected behavior**
the bui opens without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 7 64 bit

**Additional context**

**Comment by idzresearch** [comment]
Windows 7 is not supported OS,
Windows 10 would be required to run the tool.
If still want to run the tool on Windows 7, you can try workarounds like [this](https://www.youtube.com/watch?v=TQ2XAmGDLmU).
